name: Deploy Vite Frontend to Azure Web App

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies & build Vite app
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Archive Vite build
        run: |
          cd frontend/dist
          zip -r ../../build.zip ./

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'findyourhome-frontend'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: build.zip
